version: "3"

services: 
  web:
    build: ./web
    ports: 
      - "2200:22"
      - "80:80"

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080